openapi: 3.0.0
info:
  title: Gestion de profil d'utilisateur
  version: 1.0.0
components:
  parameters:
    UserId:
      name: id
      in: path
      required: true
      description: Unique identifier of the user
      schema:
        type: string

  schemas:
    PersonalInfo:
      type: object
      properties:
        first_name:
          type: string
        last_name:
          type: string
        birthdate:
          type: string
          format: date
        email:
          type: string
          format: email
      required: [first_name, last_name, email]

    Address:
      type: object
      properties:
        address_street:
          type: string
        address_city:
          type: string
        address_country:
          type: string
        address_postal_code:
          type: integer

    Preferences:
      type: object
      properties:
        needs_newsletter:
          type: boolean
        language:
          type: string
          enum: [mg, fr, eng]

    CreateUserProfile:
      allOf:
        - $ref: '#/components/schemas/PersonalInfo'
        - $ref: '#/components/schemas/Address'
        - $ref: '#/components/schemas/Preferences'

    UserProfile:
      allOf:
        - $ref: '#/components/schemas/CreateUserProfile'
        - type: object
          properties:
            identifier:
              type: string
          required: [identifier]



paths:
  /users/{id}:
    get:
      summary: Get a user by ID
      parameters:
        - $ref: '#/components/parameters/UserId'
      responses:
        '200':
          description: User profile found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
              example:
                identifier: "usr_12345"
                first_name: "Liva"
                last_name: "Rakoto"
                birthdate: "1998-07-15"
                email: "liva.rakoto@example.com"
                address_street: "Lot II A 45"
                address_city: "Antananarivo"
                address_country: "Madagascar"
                address_postal_code: 101
                needs_newsletter: true
                language: "mg"

  /users:
    post:
      summary: Create new users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/CreateUserProfile'
            example:
              - first_name: "Miora"
                last_name: "Andria"
                birthdate: "2000-05-21"
                email: "miora@example.com"
                address_street: "Rue 123"
                address_city: "Fianarantsoa"
                address_country: "Madagascar"
                address_postal_code: 301
                needs_newsletter: false
                language: "fr"
      responses:
        '201':
          description: Users created successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserProfile'

  /users/{id}/personalInfo:
    put:
      summary: Update only personal info
      parameters:
        - $ref: '#/components/parameters/UserId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PersonalInfo'
            example:
              first_name: "Miora"
              last_name: "Andrianina"
              birthdate: "2000-05-21"
              email: "miora.new@example.com"
      responses:
        '200':
          description: Updated user info
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'

  /users/{id}/address:
    put:
      summary: Update only address
      parameters:
        - $ref: '#/components/parameters/UserId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Address'
            example:
              address_street: "Avenue 456"
              address_city: "Antsirabe"
              address_country: "Madagascar"
              address_postal_code: 110
      responses:
        '200':
          description: Updated address
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'

  /users/{id}/preferences:
    put:
      summary: Update only preferences
      parameters:
        - $ref: '#/components/parameters/UserId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Preferences'
            example:
              needs_newsletter: true
              language: "eng"
      responses:
        '200':
          description: Updated preferences
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
